
name: setup-cr
description: Setup Calcit runner
inputs:
  version:
    description: "Version of Calcit to install"
    required: false
  bundler:
    description: "Whethere to download calcit bunder_command"
    required: false
    default: false

runs:
  using: node20
  main: dist/index.js

branding:
  icon: cloud-snow
  color: blue
